ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdhelm01.itm~ BEGIN
  COPY ~k0_iskp/itm/bdhelm01.itm~ ~override~
    SAY NAME1 @20165 /* Crown */
    SAY NAME2 @20167 /* Crown of Lies */
    SAY UNIDENTIFIED_DESC @20166 /* A crown can be made of any precious metal and is usually decorated with gemstones. Heavy crowns can be worn for ceremonial purposes, with lighter diadems or circlets crafted for everyday use.

STATISTICS:

Weight: 1 */
    SAY DESC @20168 /* This glittering golden crown looks impressive, but its substance is base fool's gold and the "gems" set around it are bits of colored glass. Placing the crown on one's head allows the wearer to prepare extra spells but fills the head with false knowledge.

STATISTICS:

Equipped abilities:
– Can memorize 2 extra 3rd-level, 1 extra 4th-level, and 1 extra 5th-level wizard spell
– Lore: -30

Weight: 1 */
END
COPY_EXISTING ~firkra02.cre~ ~override~
  ADD_CRE_ITEM ~bdhelm01~ #0 #0 #0 ~NONE~ ~INV~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdhelm01.bam~ BEGIN
  COPY ~k0_iskp/bam/bdhelm01.bam~ ~override~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdchlm01.bam~ BEGIN
  COPY ~k0_iskp/bam/bdchlm01.bam~ ~override~
END
