ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdbrd02.itm~ BEGIN
  COPY ~k0_iskp/itm/bdbrd02.itm~ ~override~
    SAY NAME1 @20127 /* Flute */
    SAY NAME2 @20279 /* Flute of the Immaculate Breeze */
    SAY UNIDENTIFIED_DESC @20128 /* A flute is a long, hollow instrument with holes along its length. A bard can coax a pleasing, piping tune from a flute, which is also easy to carry on the road.

STATISTICS:

Weight: 3 */
    SAY DESC @20280 /* Originally crafted by gnomes, this flute appears diminutive at first but when picked up, it assumes the proper size for the bard who wields it. Tiny engravings of flowers, winding vines, and wispy clouds cover the length of the flute. When played, the scent of flowers fill the air and nearby spectators sometimes feel the sensation of a gentle rain on their face.

STATISTICS:

Charge abilities:
– Zone of Sweet Air twice per day

Weight: 3 */
END
COPY_EXISTING ~mourner6.dlg~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~AddexperienceParty(5000)~ ~AddexperienceParty(5000) GiveItemCreate("bdbrd02",LastTalkedToBy,0,0,0)~
    REPLACE_TEXTUALLY ~#27069~ ~Yes, thank you so much. *sniff* Please, take this as a token of our thanks for bringing peace to our son.  It was to be a gift for him, and I can no longer bear to look at it.  Come, my husband... let us go home.~
  END
BUT_ONLY_IF_IT_CHANGES

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdbrd02.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdbrd02.bam~ ~override~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~cbdbrd02.bam~ BEGIN
  COPY ~k0_iskp/bam/cbdbrd02.bam~ ~override~
END
