// Herdrin's Short Sword
ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h09.itm~ BEGIN
  COPY ~k0_iskp/itm/bdsw1h09.itm~ ~override~
    SAY NAME1 @20002 /* Short Sword */
    SAY NAME2 @100184 /* Herdrin's Short Sword +2 */
    SAY UNIDENTIFIED_DESC @20003 /* The short sword is the first type of sword to come into existence. In the simplest of terms, a short sword can be considered a dagger with a blade so long that it can no longer be called a dagger. The term short sword does not exist in sword classifications. However, it has come to be used to describe a double-edged blade about two feet in length. The sword tip is usually pointed, ideal for thrusting.

STATISTICS:

Damage: 1d6 (piercing)
Speed Factor: 3
Proficiency Type: Short Sword
Type: One-handed
Requires:
 5 Strength

Weight: 3 */
    SAY DESC @100185 /* The short sword wielded by one-time caravan guard Herdrin, who died in defense of Bridgefort. The sword is of a simple and solid design, a utilitarian blade with a wolf's head carved on the pommel. Herdrin's sword strikes swiftly and keenly and serves its wielder well.

STATISTICS:

Combat abilities:
– Critical Hit Chance: +10% (this weapon)

THAC0: +2
Damage: 1d6+2 (piercing)
Speed Factor: 1
Proficiency Type: Short Sword
Type: One-handed
Requires:
 4 Strength

Weight: 2 */
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~csw1h28.bam~ BEGIN
  COPY ~k0_iskp/bam/csw1h28.bam~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~isw1h28.bam~ BEGIN
  COPY ~k0_iskp/bam/isw1h28.bam~ ~override~
END
