// Belt of the Skillfull Blade
INCLUDE ~k0_iskp/lib/components/comp_3000.tpa~
<<<<<<<< .../inlined/k0baldur.baf
IF
  Global("K0_II_BELT_OF_THE_SKILLFUL_BLADE","GLOBAL",0)
  Global("BD_SOD_IMPORT_04","GLOBAL",0)
  Global("BD_HAVE_SOD","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("BD_SOD_IMPORT_04","GLOBAL",1)
    SetGlobal("K0_II_BELT_OF_THE_SKILLFUL_BLADE","GLOBAL",1)
END
>>>>>>>>
EXTEND_BOTTOM ~ar0602.bcs~ ~.../inlined/k0baldur.baf~
