ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdkeyr.itm~ BEGIN
  COPY ~k0_iskp/itm/bdkeyr.itm~ ~override~
    SAY NAME1 @20219  /* Key Ring */
    SAY NAME2 @20219  /* Key Ring */
    SAY UNIDENTIFIED_DESC @20220  /* A latch on this heavy steel ring allows it to open on a hinge. Dozens of keys may be threaded on the ring to keep them organized.

STATISTICS:

Weight: 0 */
    SAY DESC @20220  /* A latch on this heavy steel ring allows it to open on a hinge. Dozens of keys may be threaded on the ring to keep them organized.

STATISTICS:

Weight: 0 */

  COPY ~k0_iskp/sto/bdkeyr.sto~ ~override~
    SAY NAME2 @20219  /* Key Ring */
END
COPY_EXISTING ~ar0602.are~ ~override~
  LPF fj_are_structure
    INT_VAR
      fj_con_itm_idx = 37
    STR_VAR
      fj_name           = bdkeyr
      fj_structure_type = itm
  END
BUT_ONLY

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdkeyr.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdkeyr.bam~ ~override~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~cbdkeyr.bam~ BEGIN
  COPY ~k0_iskp/bam/cbdkeyr.bam~ ~override~
END
