IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_28","GLOBAL",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_28","GLOBAL",2)
        TakeItemReplace("bdleat07","leat08","MAEVAR")  // The Night's Embrace +3 / Shadow Armor +3
        ActionOverride("MAEVAR",XEquipItem("bdleat07",Myself,SLOT_ARMOR,EQUIP)  // The Night's Embrace +3
        SetInterrupt(FALSE)
END
