IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_76","GLOBAL",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_76","GLOBAL",2)
        TakeItemReplace("bdblun04","STAF01","SLILMAT")  // Martyr's Morningstar +2
        ActionOverride("SLILMAT",XEquipItem("bdblun04",Myself,SLOT_WEAPON0,EQUIP))  // Martyr's Morningstar +2
        SetInterrupt(FALSE)
        Continue()
END
