IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_68","GLOBAL",1)
    Global("OHD_enter_terpfen","oh5300",3)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_68","GLOBAL",2)
        ActionOverride("OHDTERP",CreateItem("bdring03",0,0,0)) // Ring of the Crusade
        ActionOverride("OHDTERP",XEquipItem("bdring03",Myself,SLOT_RING_LEFT,EQUIP))  // Ring of the Crusade
        SetInterrupt(FALSE)
        Continue()
END
