IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_NEWSODITEM1","locals",0)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_NEWSODITEM1","locals",1)
        DestroyItem("SW1H04")  // Long Sword
        CreateItem("bdsw2h02",0,0,0)  // Sword of Troll Decapitation +1
        XEquipItem("bdsw2h02",Myself,SLOT_WEAPON0,EQUIP)  // Sword of Troll Decapitation +1
        SetInterrupt(FALSE)
END
