IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_FQUEENB","GLOBAL",0)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_FQUEENB","GLOBAL",1)
        ActionOverride("VAELASA",CreateItem("bdbrd01",1,0,0)) // The Forest Queen's Benediction
        ActionOverride("VAELASA",XEquipItem("bdbrd01",Myself,SLOT_MISC4,EQUIP))  // The Forest Queen's Benediction - added to Quick Item Slot 1
        SetInterrupt(FALSE)
        Continue()
END
