IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_66","GLOBAL",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_66","GLOBAL",2)
        TakeItemReplace("bdrobe01","CLCK17","MEKRATH")  // Robe of Arcane Apititude/Robe of the Evil Archmagi
        ActionOverride("MEKRATH",XEquipItem("bdrobe01",Myself,SLOT_ARMOR,EQUIP))  //Robe of Arcane Apititude
        SetInterrupt(FALSE)
END
