IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_33","GLOBAL",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_33","GLOBAL",2)
        TakeItemReplace("bddagg05","STAF01","SPPAIN")  // Acid-Etched Dagger +2
        ActionOverride("SPPAIN",XEquipItem("bddagg05",Myself,SLOT_WEAPON0,EQUIP))  // Acid-Etched Dagger +2
        SetInterrupt(FALSE)
END
