IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_17","GLOBAL",1)
    Global("LyrosSpawn","GLOBAL",2)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_17","GLOBAL",2)
        ActionOverride("LYROS",CreateItem("bdclck06",7,0,0)) // Cloak of Minor Arcana
        ActionOverride("LYROS",XEquipItem("bdclck06",Myself,SLOT_CLOAK,EQUIP))  // Robe of Arcane Aptitude
        SetInterrupt(FALSE)
END
