IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_69","GLOBAL",1)
    Global("SpawnWolfwere","AR2600",1)  // Thetyr Wood
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_69","GLOBAL",2)
        ActionOverride("c6safa",CreateItem("bdsw1h14",0,0,0)) // Fractal Blade +3
        ActionOverride("c6safa",XEquipItem("bdsw1h14",Myself,SLOT_WEAPON0,EQUIP)  // Fractal Blade +3
        SetInterrupt(FALSE)
END
