IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_BLOOMSAC","GLOBAL",0)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_BLOOMSAC","GLOBAL",1)
        ActionOverride("ICMYC02",CreateItem("bdmisc08",4,0,0)) // Myconid Bloom-Sac
        ActionOverride("ICMYC02",XEquipItem("bdmisc08",Myself,SLOT_MISC4,EQUIP))  // Myconid Bloom-Sac
        SetInterrupt(FALSE)
        Continue()
END
