IF
    Global("BD_HAVE_SOD","GLOBAL",1)
    Global("K0_SOD_IMPORT_45","GLOBAL",1)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("K0_SOD_IMPORT_45","GLOBAL",2)
        DestroyItem("BLUN13")  // Flail +2
        CreateItem("bdblun05",0,0,0)  // The Hydra +2
        XEquipItem("bdblun05",Myself,SLOT_WEAPON0,EQUIP)  // The Hydra +2
        SetInterrupt(FALSE)
        Continue()
END
