ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h02.itm~ BEGIN
  COPY ~k0_iskp/itm/bdsw1h02.itm~ ~override~
    SAY NAME1 @20000 /* Long Sword */
    SAY NAME2 @20159 /* Tongue of Acid +3 */
    SAY UNIDENTIFIED_DESC @20001 /* These swords are usually referred to as double-edged swords, war swords, or military swords. In many cases, the long sword has a single-edged blade. There is no single version of the long sword; the design and length vary from culture to culture and may vary within the same culture depending on the era. Among the most common characteristics of all long swords is their length, which ranges from thirty-five inches to forty-seven inches. In the latter case, the blade is known to take up forty inches of the total length. Most long swords have a double-edged blade and a sharp point at the tip. Despite the tip, the long sword is designed for slashing, not thrusting.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 4 */
    SAY DESC @20160 /* This infernal longsword, forged to resemble a devil's tongue, has a blade "sharper than any scream" according to the writing on the hilt. Its edge cuts easily through armor and bone and leaves acid sizzling in the wounds it inflicts. The pain its wounds inflict is so severe that its victims have difficulty functioning, even walking, due to the agony.

STATISTICS:

Combat abilities:
– 10% chance per hit of slowing the target for 3 rounds (Save vs. Spell negates)

THAC0: +3
Damage: 1d8+3, +1d3 (acid)
Damage Type: Slashing
Speed Factor: 2
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 2 */
  COPY ~k0_iskp/spl/bdsw1h02.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40007 /* Slowed */)
    END
END
<<<<<<<< .../inlined/k0ar1402.baf
IF
  Global("K0_ITEMS_BDSW1H22","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("K0_ITEMS_BDSW1H22","GLOBAL",1)
    ActionOverride("SHADRA01",CreateItem("bdsw1h02",0,0,0))
    SetInterrupt(FALSE)
END
>>>>>>>>
EXTEND_BOTTOM ~ar1402~ ~.../inlined/k0ar1402.baf~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibds1h02.bam~ BEGIN
  COPY ~k0_iskp/bam/ibds1h02.bam~ ~override~
END
