ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdrobe01.itm~ BEGIN
  COPY ~k0_iskp/itm/bdrobe01.itm~ ~override~
    SAY NAME1 @20079 /* Mage Robe */
    SAY NAME2 @20311 /* Robe of Arcane Aptitude */
    SAY UNIDENTIFIED_DESC @20080 /* Since the age of Netheril, mages have learned to bestow a wide variety of magical properties upon the everyday objects that surround them. A favorite item of such enchantment is the common robe. It is lightweight, affordable, and holds its enchantment well, thereby making it ideal equipment for a mage. Due to their magical heritage, however, only single-, dual-, and multi-class Mages may wear these enchanted robes.

STATISTICS:

Weight: 3 */
    SAY DESC @20312 /* The provenance of this dark purple robe has been lost in the mists of history, but a faint odor of stale magic lingers in the air around the threadbare garment. The one who wore it was clearly no stranger to the Weave. Closely examining the robe, you are able to pick out a stylized flame design woven into the fabric. It seems likely the intricate pattern was always subtle, but even were that not true, countless years of wear have rendered the flames all but invisible.

STATISTICS:

Equipped abilities:
– Intelligence: +1
– Armor Class: 5

Charge abilities:
– Spell Sequencer once per day

Weight: 3 */
END
OUTER_SET ability1 = RESOLVE_STR_REF(@5035 /* Spell Sequencer */)
APPEND ~tooltip.2da~ ~bdrobe01  %ability1%  -1  -1~ BUT_ONLY
COPY_EXISTING ~tooltip.2da~ ~override~
  LPF a7#normalize_table
  END
BUT_ONLY
<<<<<<<< .../inlined/k0ar0300.baf
IF
  Global("K0_ITEMS_BDROBE01","GLOBAL",0)
  Global("LyrosSpawn","GLOBAL",2)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("K0_ITEMS_BDROBE01","GLOBAL",1)
    ActionOverride("LYROS",CreateItem("bdclck06",7,0,0)) // Cloak of Minor Arcana
    ActionOverride("LYROS",XEquipItem("bdclck06",Myself,SLOT_CLOAK,EQUIP))  // Robe of Arcane Aptitude
    SetInterrupt(FALSE)
END
>>>>>>>>
EXTEND_BOTTOM ~ar0300.bcs~ ~.../inlined/k0ar0300.baf~
COPY_EXISTING ~ar0300.are~ ~override~
  WRITE_ASCII AREA_SCRIPT ~ar0300~ #8
BUT_ONLY

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdrob01.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdrob01.bam~ ~override~
END
