ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h25.itm~ BEGIN
  COPY ~k0_iskp/itm/bdsw1h25.itm~ ~override~
    SAY NAME1 @20000
    SAY NAME2 @20319
    SAY UNIDENTIFIED_DESC @20001
    SAY DESC @20320
  COPY ~k0_iskp/spl/bdsw1h25.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40028)
    END
  COPY ~k0_iskp/eff/bdsw1h25.eff~ ~override~
END
COPY_EXISTING ~bshop02.sto~ ~override~
  ADD_STORE_ITEM ~bdsw1h25~ #1 #0 #0 ~IDENTIFIED~ #1
