ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdbelt03.itm~ BEGIN
  COPY ~k0_iskp/itm/bdbelt03.itm~ ~override~
    SAY NAME1 @20109 /* Belt */
    SAY NAME2 @20263 /* Belt of the Cunning Rogue */
    SAY UNIDENTIFIED_DESC @20110 /* Girdles are generally similar to belts. Unlike belts, girdles are not used to hold up pants and dungarees, but to carry pouches, scabbards, and the like.

STATISTICS:

Weight: 2 */
    SAY DESC @20264 /* This wide leather belt has been dyed a deep magenta. The belt was created over a decade ago by a human thief who saw his larcenous activities as a means of worshiping Mask. All his burglaries were undertaken with prayers to Mask, and he hoarded his stolen goods at a hidden altar to the god of thieves. He favored purple clothing, believing it was a color the god preferred, and he crafted this belt to match his ensemble. The thief was eventually caught and killed on one of his missions and the belt confiscated by the city guard. The next night, the belt vanished from a locked chest in the guardhouse, though, whisked away by Mask so that it could continue to serve the god's ends. Even today, the belt often finds its way into the path of those who will put it to good use.

The pouches attached to the belt contain a number of small tools, wires, picks, and blades that can be used to pick locks and disable traps.

STATISTICS:

Equipped abilities:
– Open Locks: +15%
– Find Traps: +15%

Weight: 2 */
END
COMPILE ~k0_iskp/dlg/k0roger.d~  // Belt of the Cunning Rogue

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdblt03.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdblt03.bam~ ~override~
END
