// Bullet of Darkness +3
ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdbull02.itm~ BEGIN
  COPY ~k0_iskp/itm/bdbull02.itm~ ~override~
    SAY NAME2 @100117 /* Bullet of Darkness +3 */
    SAY DESC @100118 /* Though it appears to be nothing more than standard sling ammunition, one who handles this bullet will soon realize it is far more than that. Specially made by Jegg Hillcarver of Bridgefort, within the missile's metal surface are shards of voidstone. Highly dangerous, if not outright lethal, to most targets, the bullet's one great deficiency is in its utility against the undead. Objects of the Negative Material Plane have no effect on the unliving; neither then does this most unique item.

STATISTICS:

Combat abilities:
– The target suffers -1 to Strength for 5 rounds per hit (minimum 1 Strength; Save vs. Spell negates).
– Does no damage to the undead

THAC0: +3
Damage: 1d4+4 (magic)
Launcher: Sling

Weight: 0 */
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dtkmaghl.vvc~ BEGIN
  COPY ~k0_iskp/vvc/dtkmaghl.vvc~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~dtkmaghl.bam~ BEGIN
  COPY ~k0_iskp/bam/dtkmaghl.bam~ ~override~
END
COPY_EXISTING ~bdbull02.itm~ ~override~
  LPF CLONE_EFFECT
    INT_VAR
      match_opcode     = 12
      match_parameter2 = 4194304
      opcode           = 215
      parameter2       = 0
    STR_VAR
      resource   = dtkmaghl
      dicenumber = 0
      dicesize   = 0
      timing     = 0
  END
BUT_ONLY IF_EXISTS
COPY_EXISTING ~shop04.sto~ ~override~  // Enge's Shop
  ADD_STORE_ITEM ~bdbull02~ #1 #0 #0 ~IDENTIFIED~ #80
