ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdblun05.itm~ BEGIN
  COPY ~k0_iskp/itm/bdblun05.itm~ ~override~
    SAY NAME1 @20037  /* Flail */
    SAY NAME2 @20267  /* The Hydra +2 */
    SAY UNIDENTIFIED_DESC @20038  /* The flail is a sturdy wooden handle attached to an iron rod, a wooden rod with spikes, or a spiked iron ball. Between the handle and its implement is either a hinge or chain link. The weapon was originally used as a tool for threshing grain.

STATISTICS:

Damage: 1d6+1 (crushing)
Speed Factor: 7
Proficiency Type: Flail/Morning Star
Type: One-handed
Requires:
 13 Strength

Weight: 15 */
    SAY DESC @20268  /* The three heads of this flail look like dragon heads, giving the weapon its fearsome name. As the weilder swings the weapon, its heads seem to blur and divide until a mass of hydra heads whips from the end of the chain. When the weilder ceases attacking, the weapon reverts to its original appearance.

STATISTICS:

Combat abilities:
– 33% chance per hit of dealing +1d4, +2d4, or +3d4 points of piercing damage

THAC0: +2
Damage: 1d6+3 (crushing)
Speed Factor: 5
Proficiency Type: Flail/Morning Star
Type: One-handed
Requires:
 13 Strength

Weight: 12 */
END
COPY_EXISTING ~roger.sto~ ~override~  // Roger the Fence
  ADD_STORE_ITEM ~bdblun05~ #0 #0 #0 ~IDENTIFIED~ #1

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdbln05.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdbln05.bam~ ~override~
END
