ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h21.itm~ BEGIN
  COPY ~k0_iskp/bam/ibds1h21.bam~ ~override~
  COPY ~k0_iskp/itm/bdsw1h21.itm~ ~override~
    SAY NAME1 @20002 /* Short Sword */
    SAY NAME2 @20141 /* Vexation +2 */
    SAY UNIDENTIFIED_DESC @20003 /* The short sword is the first type of sword to come into existence. In the simplest of terms, a short sword can be considered a dagger with a blade so long that it can no longer be called a dagger. The term short sword does not exist in sword classifications. However, it has come to be used to describe a double-edged blade about two feet in length. The sword tip is usually pointed, ideal for thrusting.

STATISTICS:

Damage: 1d6 (piercing)
Speed Factor: 3
Proficiency Type: Short Sword
Type: One-handed
Requires:
 5 Strength

Weight: 3 */
    SAY DESC @20142 /* This blade appears smooth and whole at first glance, but on closer examination, its surface is made of thousands of tiny overlapping scales. When the sword is used to stab a target unawares, scales break off and lodge in the wound, irritating the victim and draining their strength.

STATISTICS:

Combat abilities:
– Inflicts 2 points of bleeding damage per hit (one point per round)
– Drains 2 points of Strength from the target and transfers them to the weilder for 5 rounds when a successful backstab is performed (non-cumulative)

STATISTICS:

THAC0: +2
Damage: 1d6+2 (piercing)
Speed Factor: 1
Proficiency Type: Short Sword
Type: One-handed
Requires:
 4 Strength

Weight: 2 */
  COPY ~k0_iskp/spl/bdstrdrn.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode     = 139
        match_parameter1 = 14042
        parameter1       = RESOLVE_STR_REF(@40000 /* Strength Modification */)
    END
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode     = 139
        match_parameter1 = 1452
        parameter1       = RESOLVE_STR_REF(@40001 /* Strengthened */)
    END
  COPY ~k0_iskp/spl/bdsw1h21.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40002 /* Bleeding */)
    END
END
COPY_EXISTING ~pirsea01.cre~ ~override~
  REPLACE_CRE_ITEM ~bdsw1h21~ #0 #0 #0 ~NONE~ ~WEAPON~ EQUIP
