// Tangled Strings
<<<<<<<< .../inlined/k0baldur.baf
IF
  Global("K0_IMPORT_ITEMS_TANGLED_STRINGS","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("BD_HAVE_SOD","GLOBAL",1)  // Core variable needed for all items to import
    SetGlobal("BD_SOD_IMPORT_09","GLOBAL",1)  // Tangled Strings
    SetGlobal("K0_IMPORT_ITEMS_TANGLED_STRINGS","GLOBAL",1)
END
>>>>>>>>
EXTEND_BOTTOM ~baldur.bcs~ ~.../inlined/k0baldur.baf~
