ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h25.itm~ BEGIN
  COPY ~k0_iskp/itm/bdsw1h25.itm~ ~override~
    SAY NAME1 @20000 /* Long Sword */
    SAY NAME2 @20319 /* Spell Breaker +2 */
    SAY UNIDENTIFIED_DESC @20001 /* These swords are usually referred to as double-edged swords, war swords, or military swords. In many cases, the long sword has a single-edged blade. There is no single version of the long sword; the design and length vary from culture to culture and may vary within the same culture depending on the era. Among the most common characteristics of all long swords is their length, which ranges from thirty-five inches to forty-seven inches. In the latter case, the blade is known to take up forty inches of the total length. Most long swords have a double-edged blade and a sharp point at the tip. Despite the tip, the long sword is designed for slashing, not thrusting.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 4 */
    SAY DESC @20320 /* Power can corrupt even the noblest of mages, and the long-lived elves of Faerûn have seen what devastating consequences can occur when a mage loses control. This elegant longsword, its silver hilt decorated with clear blue gems, was crafted to deal with arcane spellcasters who have abused their gift. The sword assists any hunter who tracks down out-of-control mages, and has particular potency in the hands of wizard slayers or inquisitors.

STATISTICS:

Equipped abilities:
– Save vs. Spell: +4 (Wizard Slayers and Inquisitors), +2 (others)

Combat abilities:
– On a critical hit, the target is affected by Dispel Magic

THAC0: +2
Damage: 1d8+2 (slashing)
Speed Factor: 3
Proficiency Type: Long Sword
Type: One-handed
Requires:
 6 Strength

Weight: 3 */
  COPY ~k0_iskp/spl/bdsw1h25.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40028 /* Dispel Effects */)
    END
  COPY ~k0_iskp/eff/bdsw1h25.eff~ ~override~
END
COPY_EXISTING ~bshop02.sto~ ~override~
  ADD_STORE_ITEM ~bdsw1h25~ #1 #0 #0 ~IDENTIFIED~ #1

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibds1h25.bam~ BEGIN
  COPY ~k0_iskp/bam/ibds1h25.bam~ ~override~
END
