ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdsw1h03.itm~ BEGIN
  COPY ~k0_iskp/itm/bdsw1h03.itm~ ~override~
    SAY NAME1 @20006 /* Scimitar */
    SAY NAME2 @20315 /* Eadro's Blade +1 */
    SAY UNIDENTIFIED_DESC @20007 /* The long, curved, single-edged blade is characteristic of both the saber and the scimitar, even though their origins lie in different parts of Faerûn. Whereas the saber was intended chiefly for horsemen, mainly due to its versatility, the scimitar has a heavier oriental influence. The "shamshir," as it was originally called, is larger, more highly curved, and tapered to an elongated, sharp point. This makes the weapon slightly slower but more effective and deadly in combat.

STATISTICS:

Damage: 1d8 (slashing)
Speed Factor: 5
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 4 */
    SAY DESC @20316 /* Legend has it that this elegant curving blade was forged deep beneath the sea by merfolk and its hilt bound in enchanted eelskin. The truth of the matter is more mundane. The blade was crafted in Iriaebor and given to a mercenary commander who protected cargo barges moving up and down the river Chionthar. Still, it is a finely made and serviceable weapon.

STATISTICS:

Equipped abilities:
– Armor Class: +2 vs. elementals and mephits

Combat abilities:
– A critical hit against an elemental or mephit will instantly banish the creature to its home plane

THAC0: +1, +2 vs. elementals and mephits
Damage: 1d8+1, +2 vs. elementals and mephits
Damage Type: Slashing
Speed Factor: 4
Proficiency Type: Scimitar/Wakizashi/Ninjatō
Type: One-handed
Requires:
 10 Strength

Weight: 3 */
  COPY ~k0_iskp/spl/bdsw1h03.spl~ ~override~
  COPY ~k0_iskp/spl/bdsw1h3b.spl~ ~override~
    SAY NAME1 @40026 /* Banishment */
  COPY ~k0_iskp/eff/bdsw1h3d.eff~ ~override~
  COPY ~k0_iskp/eff/bdsw1h3h.eff~ ~override~
  COPY ~k0_iskp/eff/bdsw1h3m.eff~ ~override~
END
<<<<<<<< .../inlined/k0ar0601.baf
IF
  Global("K0_ITEMS_BDSW1H03","GLOBAL",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("K0_ITEMS_BDSW1H03","GLOBAL",1)
    ActionOverride("Container 1",CreateItem("bdsw1h03",0,0,0)) // Eadro's Blade +1
    SetInterrupt(TRUE)
END
>>>>>>>>
EXTEND_BOTTOM ~ar0601.bcs~ ~.../inlined/k0ar0601.baf~
COPY_EXISTING ~ar0601.are~ ~override~
  WRITE_ASCII AREA_SCRIPT ~ar0601~ #8
BUT_ONLY

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibds1h03.bam~ BEGIN
  COPY ~k0_iskp/bam/ibds1h03.bam~ ~override~
END
