ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdxbow01.itm~ BEGIN
COPY ~k0_iskp/itm/bdxbow01.itm~ ~override~
SAY NAME1 @20059
SAY NAME2 @20221
SAY UNIDENTIFIED_DESC @20060
SAY DESC @20222
WRITE_SHORT 0x42 0  // Setting lore value to 0 to prevent need to identify
COPY ~k0_iskp/eff/bdxbow1h.eff~ ~override~
COPY ~k0_iskp/eff/bdxbow1d.eff~ ~override~
COPY ~k0_iskp/spl/bdxbow01.spl~ ~override~
END
EXTEND_BOTTOM ~keldorn.bcs~ ~k0_iskp/baf/k0keldo.baf~  // Astral Crossbow +2
