// All VoidHammer
INCLUDE ~k0_iskp/lib/comp_3000.tpa~
INCLUDE ~k0_iskp/lib/comp_3002.tpa~
INCLUDE ~k0_iskp/lib/comp_3003.tpa~
INCLUDE ~k0_iskp/lib/comp_3004.tpa~
INCLUDE ~k0_iskp/lib/comp_3005.tpa~
INCLUDE ~k0_iskp/lib/comp_3006.tpa~
INCLUDE ~k0_iskp/lib/comp_3007.tpa~
INCLUDE ~k0_iskp/lib/comp_3008.tpa~
INCLUDE ~k0_iskp/lib/comp_3009.tpa~
INCLUDE ~k0_iskp/lib/comp_3010.tpa~
INCLUDE ~k0_iskp/lib/comp_3011.tpa~
