ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdxbow02.itm~ BEGIN
  COPY ~k0_iskp/itm/bdxbow02.itm~ ~override~
    SAY NAME1 @20061
    SAY NAME2 @20327
    SAY UNIDENTIFIED_DESC @20062
    SAY DESC @20328
  COPY ~k0_iskp/spl/bddoom.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40029)
    END
END
COPY_EXISTING ~resuna.cre~ ~override~
  ADD_CRE_ITEM ~bdxbow02~ #0 #0 #0 ~NONE~ ~WEAPON~ EQUIP TWOHANDED
