ACTION_IF NOT FILE_EXISTS_IN_GAME ~bdclck05.itm~ BEGIN
  COPY ~k0_iskp/itm/bdclck05.itm~ ~override~
    SAY NAME1 @20107 /* Cloak */
    SAY NAME2 @20329 /* Cloak of the Gargoyle */
    SAY UNIDENTIFIED_DESC @20108 /* The cloak can be made in every possible shape with just about every type of fabric. The most common forms are a circular piece of fabric with a hole in the center for the head, and fabric draped from neck, connected by a chain, brooch, cord, or pins.

STATISTICS:

Weight: 3 */
    SAY DESC @20340 /* Though this dark gray cloak appears to be made of stone, it is soft and flexible as cloth. When donned, it allows its wearer to assume a statue-like form once per day. These cloaks are often found among the duergar, who first designed them, but occasionally one winds up on the surface.

STATISTICS:

Equipped abilities:
– Physical Damage Resistance: +5%
– Protects against critical hits

Charge abilities:
– Stone Form once per day
  Armor Class: 0
  Saving Throws: +3
  Dexterity: -3
  Duration: 5 turns

Weight: 2 */
  COPY ~k0_iskp/spl/bdstonef.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
        match_opcode = 139
        parameter1   = RESOLVE_STR_REF(@40030 /* Stone Form */)
    END
END
OUTER_SET ability1 = RESOLVE_STR_REF(@40030 /* Stone Form */)
APPEND ~tooltip.2da~ ~bdclck05  %ability1%  -1  -1~ BUT_ONLY
COPY_EXISTING ~tooltip.2da~ ~override~
  LPF a7#normalize_table
  END
BUT_ONLY
<<<<<<<< .../inlined/k0udsol.d
EXTEND_BOTTOM UDSVIR05 6
  IF ~Global("K0_ITEMS_BDCLCK05","GLOBAL",0)~
    THEN DO ~SetGlobal ("K0_ITEMS_BDCLCK05","GLOBAL",1)
    GiveItemCreate("bdhamm01",LastTalkedToBy,0,0,0)~ GOTO K0SODIMP
END

APPEND UDSVIR05
  IF ~~ THEN BEGIN K0SODIMP
    SAY @80008
    COPY_TRANS UDSVIR05 6
  END
END
>>>>>>>>
COMPILE ~.../inlined/k0udsol.d~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~ibdclk05.bam~ BEGIN
  COPY ~k0_iskp/bam/ibdclk05.bam~ ~override~
END
