// Helm of Dumathoin
<<<<<<<< .../inlined/k0baldur.baf
IF
  Global("K0_II_HELM_OF_DUMATHOIN","GLOBAL",0)
  Global("BD_SOD_IMPORT_06","GLOBAL",0)
  Global("BD_HAVE_SOD","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("BD_SOD_IMPORT_06","GLOBAL",1)
    SetGlobal("K0_II_HELM_OF_DUMATHOIN","GLOBAL",1)
END
>>>>>>>>
EXTEND_BOTTOM ~baldur.bcs~ ~.../inlined/k0baldur.baf~
COPY_EXISTING ~bdhelm09.itm~ ~override~	//Fixing description image for Helmet of Dumathoin
  WRITE_ASCII 0x58 dtkhdum1
END
